version: "3.6"

services:
  thisrepo-testing:
    image: "indigodatacloud/ci-images:python3.10"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    volumes:
      - type: bind
        source: ./
        target: /srv
